# This file contains matchings between labels (keys) and PR branches where the labels should be applied (values).
#
# Any PR with a branch matching any of the ones inside the list will be auto-labeled with the correspondent label.

":rocket: feature": ["enhancement/*", "feature/*", "feat/*"]
":blue_book: documentation": ["docs/*", "documentation/*", "doc/*"]
":warning: breaking": ["breaking/*", "break/*"]
":beetle: bug": ["bug/*", "fix/*"]
":lipstick: style": ["style/*", "format/*"]
":package: refactor": ["refactor/*"]
":broom: cleaning": ["remove/*", "clean/*"]
":wrench: build": ["build/*"]
":test_tube: test": ["test/*", "tests/*", "testing/*"]
":chart_with_upwards_trend: dependency-update": ["update/*", "dep/*", "dependency/*", "dependency-update/*", "updates"]
