# Runs `sbt ci-test` on the project on differnt JDKs (this task should be added to the project as a command alias
# containing the necessary steps to compile, check formatters, launch tests...).
#
# An example of this `ci-test` alias can be found in https://github.com/alejandrohdezma/sbt-github/blob/main/build.sbt.
#
# It will also do the following:
#
# - It will automatically label PRs based on head branch.
# - It will automatically enable auto-merge on `Scala Steward` PRs.
# - On Scala Steward PRs it will launch formatters and the `generateCiFiles` task and push the results to the same PR.

name: CI

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  labeler:
    if: github.event.pull_request.state == 'OPEN' && github.actor != 'dependabot[bot]'
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Update PR labels
        uses: alejandrohdezma/actions/labeler@v1
        if: github.event.pull_request.head.repo.full_name == github.repository

      - name: Check PR labels
        uses: alejandrohdezma/actions/label-check@v1

  ci-steward:
    if: |
      github.event.pull_request.state == 'OPEN' && github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.user.login == 'alejandrohdezma-steward[bot]'
    name: (Scala Steward) Enable auto-merge, run `sbt fix`...
    runs-on: ubuntu-latest
    steps:
      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/github-app-token@v1
        id: github_app
        with:
          token: ${{ secrets.GH_APP_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.3
        with:
          token: ${{ steps.github_app.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Enable auto-merge for this PR
        run: gh pr merge --auto --merge ${{github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{ steps.github_app.outputs.token }}

      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # v3.4.1
        with:
          distribution: "liberica"
          java-version: "17"
          cache: "sbt"

      - name: Run `sbt generateCiFiles`
        run: sbt generateCiFiles

      - name: Commit changes by `sbt generateCiFiles`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `sbt generateCiFiles`

      - name: Run `sbt fix`
        run: sbt fix

      - name: Commit changes by `sbt fix`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `sbt fix`

  test:
    needs: [ci-steward]
    if: |
      always() && !contains(needs.*.result, 'failure') && github.event.pull_request.state == 'OPEN' &&
        github.actor != 'dependabot[bot]'
    name: Run "sbt ci-test" on JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk:
          - 11
          - 17
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # v3.4.1
        with:
          distribution: "liberica"
          java-version: ${{ matrix.jdk }}
          cache: "sbt"

      - name: Run `sbt ci-test`
        run: sbt ci-test
