# This workflow will update PRs that are out-of-sync with the `main` branch.

name: CI

on:
  push:
    branches: [main]

jobs:
  auto-update-outdated-prs-to-latest-main:
    name: Update outdated PRs to latest `main`
    runs-on: ubuntu-latest
    steps:
      - name: Get the GitHub App installation token
        uses: alejandrohdezma/actions/github-app-token@v1
        id: github_app
        with:
          token: ${{ secrets.GH_APP_TOKEN }}

      - name: Update outdated PRs to latest `main`
        uses: alejandrohdezma/actions/update-outdated-prs@v1
        with:
          github-token: ${{ steps.github_app.outputs.token }}
