# This workflow performs two tasks:
#
# - Creates a release of the project by running `sbt ci-publish` (this task should be added to the project as a command 
#   alias containing the necessary steps to do a release). An example of the `ci-publish` alias can be found in
#   https://github.com/alejandrohdezma/sbt-github/blob/main/build.sbt.
#
# - Runs `sbt ci-docs` on the project and pushes a commit with the changes (the `ci-docs` task should be added to the 
#   project as a command alias containing the necessary steps to update documentation: re-generate docs files, 
#   publish websites, update headers...). And example of the `ci-docs` alias can be found in
#   https://github.com/alejandrohdezma/sbt-github/blob/main/build.sbt.
#
# This workflow will launch on pushed tags. Alternatively one can launch it manually using a "workflow dispatch" to
# create a snapshot release.

name: Release

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  release-snapshot:
    if: github.event_name == 'workflow_dispatch'
    name: Release a new snapshot version of the artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Enable Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:1.8
          apps: sbt
      - name: Release new version
        run: sbt ci-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  release:
    if: github.event_name == 'push'
    name: Release a new version of the artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project (current ref)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Enable Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:1.8
          apps: sbt
      - name: Release new version
        run: sbt ci-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  update_documentation:
    if: github.event_name == 'push'
    name: Updates documentation
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout project (main branch)
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Generate documentation
        run: sbt ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "Update documentation [skip ci]"
