# This workflow performs two tasks:
#
# - Creates a release of the project by running `sbt ci-publish` (this task should be added to the project as a command
#   alias containing the necessary steps to do a release). An example of the `ci-publish` alias can be found in
#   https://github.com/alejandrohdezma/sbt-github/blob/main/build.sbt.
#
# - Runs `sbt ci-docs` on the project and pushes a commit with the changes (the `ci-docs` task should be added to the
#   project as a command alias containing the necessary steps to update documentation: re-generate docs files,
#   publish websites, update headers...). An example of the `ci-docs` alias can be found in
#   https://github.com/alejandrohdezma/sbt-github/blob/main/build.sbt.
#
# This workflow will launch on pushed tags. Alternatively one can launch it manually using a "workflow dispatch" to
# create a snapshot release (this won't trigger the documentation update).

name: Release

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  release:
    name: Release a new version of the artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5
        with:
          fetch-depth: 0

      - name: Run `sbt ci-publish`
        uses: alejandrohdezma/actions/scala@v1
        with:
          jvm: adopt:1.8
          task: ci-publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  documentation:
    needs: [release]
    if: github.event_name == 'push'
    name: Updates documentation after latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Run `sbt ci-docs`
        uses: alejandrohdezma/actions/scala@v1
        with:
          jvm: adopt:1.8
          task: ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Commit changes by `sbt ci-docs`
        uses: alejandrohdezma/actions/commit-and-push@v1
        with:
          message: Run `sbt ci-docs`
